### ISSUE TITLE
cleanup queue debugging help

### ISSUE THREAD

**Issue by keen99** [pintsized/ledge#124]
folks,

so my ledge cache in redis seems to be growing again.   It appears that the queue runners aren't doing their thing to purge old entities?

53k ql:j keys - each ql:j is a job, right?  That key should get deleted when the job is complete?

```
32561 ledge:cache
   1 ql:completed
53822 ql:j
   1 ql:queues
 112 ql:s
   1 ql:t
   1 ql:tags
```

I'm not seeing anything particular in the logs - any suggestions for where to start debugging this?  I've got 3-4 ledge's pointed at this redis.

I ran my stale-entities-purge script (that I used to purge the cache after fixing the runners last time) - and of the  18608 ledge cache keys 9802 are active, leaving 8816 orphaned again - which would make sense if the jobs aren't being run.

init.lua
```
local ledge_m = require "ledge.ledge"
ledge = ledge_m.new()
ledge:config_set("redis_host",.....
```    

nginx.conf section
```
    init_by_lua_file lualib/init.lua;

    init_worker_by_lua_block {
      ledge:run_workers()
    }
```

**Comment by pintsized** [comment]
Hmm, strange. What version of Ledge are you running?

**Comment by keen99** [comment]
roughly 7b8fc8ecdc73ce3a2fffe4fa7e4e8c4e7beb0e9f with a few modifications (primarily redis timeouts and adding a header to cache responses derived from saved_ts/generated_ts)

**Comment by keen99** [comment]
ah, there we go, I knew I had this somewhere:  

```
  https://github.com/pintsized/ledge @ v0.01-745-g2f1ff42 WITH PATCH
  https://github.com/pintsized/lua-resty-qless @ 12539f7
  https://github.com/cloudflare/lua-resty-cookie @ 8b9e467
  https://github.com/hamishforbes/lua-ffi-zlib @ ad6ec96
  https://github.com/pintsized/lua-resty-http @ f1e7381
  https://github.com/pintsized/lua-resty-redis-connector @ 4b8743f
```

**Comment by keen99** [comment]
is there a debug level I can turn on, or some logging I can stuff in place somewhere to get some data on what the workers are doing (or not doing) ?

**Comment by pintsized** [comment]
You can raise your Nginx log level to DEBUG and you'll get all kinds of state machine info both for requests and from the workers. But errors will be logged anyway, so if you're not getting errors, I'm not sure you'll see much of interest from the debug log.

Do you have failed jobs in Qless? The web interface might make things easier to see: https://github.com/hamishforbes/lua-resty-qless-web

Generally, I would try to keep Ledge and all other modules at the latest release, and do anything custom outside of it. For example, your redis timeout issue is fixed in the latest lua-resty-qless and you can update headers by binding to the "before_save" event, in config, rather than changing the source code.

I only say this because there have been lots of incremental changes lately, so it's kinda hard to imagine what might be going on in an older version.

Anyway, yes it's weird if you have orphaned entities - that shouldn't happen under normal circumstances. I presume that's what your script is confirming? i.e. I'm not clear from your first post if you're just seeing longer than desired Qless job history, or larger than expected expired cache (make sure you understand the `keep_cache_for` directive - it's designed to keep old stuff around for ages) - or if what you're seeing is actually orphaned entities for a cache entry not being collected?

**Comment by keen99** [comment]
I definitely have orphaned entities again - (originally because I had no workers running - fixed that, wrote a tool to purge them)

I got qless-web working:

![image](https://cloud.githubusercontent.com/assets/1108844/17415577/83a1d3f8-5a58-11e6-9172-51a537e4be03.png)

![image](https://cloud.githubusercontent.com/assets/1108844/17415605/98d43676-5a58-11e6-9889-2279f4ebded5.png)


To explain our use case:

We cache objects for 1 year (there's only a few thousand objects) because they're expensive (in dollars) to re-fetch from upstream, and upstream doesn't support client caching ( if-modified-since, etc etc) since they're in the business of selling requests, and most of the data doesnt change (historical statistics).

A select group of objects get refreshed frequently during a period of the day (live events) - when that happens my clients set max-age as apropos, ledge re-fetches (and/or serves stale due to upstream timeouts.)   max stale is also 1 year.

We generally dont expect expires to happen - but may manually trigger purges.  Most of the background cleanup work would be cleaning up leftover entities after updating an object.


Typically our redis memory usage is pretty flat since growth is minimal:

![image](https://cloud.githubusercontent.com/assets/1108844/17416179/031e161c-5a5b-11e6-92cd-ba56523631c5.png)

The sharp drop was disabling replication in prep for an API key change, which would increase our cache (until purging the old keys) - effectively halving our memory usage.   The next growth is that key change, then a short period of flat - we've pulled all of the objects at that point.     THEN (by appearances) the background cleanup of stopped working - so our memory footprint has grown again, without dropping back.   Replication has not been reenabled yet.

I noticed this after PURGE'ing the old API keyed cache - I was expecting a drop. :)

On my test redis (with only a subset of the cache), using the exact same nginx/ledge config that PURGE went well:

![image](https://cloud.githubusercontent.com/assets/1108844/17416382/db403566-5a5b-11e6-9d91-892e5f07a7c6.png)



So - here I am trying to debug qless, I guess. :)

**Comment by keen99** [comment]
sadly not a lot of useful information out of debug logs at this stage (idle ledge with no http requests, so only logs are worker)

```
2016/08/04 20:02:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:02:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:02:27 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:02:27 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:02:27 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:02:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:02:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:02:27 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:05:12 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:05:12 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:05:12 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:05:12 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:05:13 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:05:13 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:05:13 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:05:13 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:07:32 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:07:32 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:07:33 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:07:33 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:07:33 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:07:33 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:07:33 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:07:33 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:10:11 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:10:11 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:10:12 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:10:12 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:10:12 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:10:12 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:10:12 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:10:12 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:11:12 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:11:12 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:11:13 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:11:13 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:11:13 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:11:13 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:11:13 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:11:13 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:12:25 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:12:25 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:12:25 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:12:25 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:12:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:12:27 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:12:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:12:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:12:27 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:17:24 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:17:24 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:17:25 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:17:25 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:17:25 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:17:25 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:17:25 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:17:25 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:17:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:17:27 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:18:32 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:18:32 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:18:33 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:18:33 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:18:33 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:18:33 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:18:33 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:18:33 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:22:12 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:22:12 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:22:13 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:22:13 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:22:13 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:22:13 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:22:13 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:22:13 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
2016/08/04 20:23:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: init_worker
2016/08/04 20:23:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: connecting_to_redis
2016/08/04 20:23:26 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: redis_connected
2016/08/04 20:23:26 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: running_worker
2016/08/04 20:23:27 [debug] 10#0: [lua] ledge.lua:2051: e(): #e: worker_finished
2016/08/04 20:23:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: redis_close
2016/08/04 20:23:27 [debug] 10#0: [lua] ledge.lua:2036: e(): #a: httpc_close
2016/08/04 20:23:27 [debug] 10#0: [lua] ledge.lua:2041: e(): #t: exiting_worker
```

**Comment by keen99** [comment]
ok, tracked down my problem.

the workers are working and cleaning up data (confirmed in the completed jobs history in  qless-web) (though I do still have a few hundred orphans again) - but the default configs for qless are what was killing me.

keeping 50,000 job history keys around as the trouble.

I wasn't able to get qless to configure in my lua, nor in ledge.lua where the background jobs are inited, so I ended up directly overriding the defaults.

![image](https://cloud.githubusercontent.com/assets/1108844/17606121/ce12161c-5feb-11e6-97e7-a7cf5b62ffa3.png)

I'm going to purge my orphans one more time - and hopefully this will get us sorted.

#114 seems directly relevant here...
